"""Isolated Windows worker for the official ``pyvroom`` package.

The main application deliberately does not import the native VROOM extension.
It writes one trusted local VROOM JSON problem, starts this worker, and reads a
JSON result.  Using ``Input.from_json`` is intentional: the high-level matrix
setters in pyvroom 1.15.2 are incompatible with the NumPy version used by the
current Python 3.14 runtime on Windows.
"""

from __future__ import annotations

import argparse
from datetime import timedelta
import importlib.metadata
import json
import os
from pathlib import Path
import sys
import tempfile
import uuid


PROTOCOL_VERSION = 1
SOLVER_BACKEND = "vroom"
REQUIRED_PYVROOM_VERSION_PREFIX = "1.15"


def _solver_version() -> str:
    return importlib.metadata.version("pyvroom")


def _require_runtime():
    try:
        import vroom
    except Exception as exc:  # pragma: no cover - exercised by frozen worker checks.
        raise RuntimeError(f"pyvroom could not be imported: {exc}") from exc

    version = _solver_version()
    if not version.startswith(REQUIRED_PYVROOM_VERSION_PREFIX):
        raise RuntimeError(
            f"This worker requires pyvroom {REQUIRED_PYVROOM_VERSION_PREFIX}.*, "
            f"but found {version}."
        )
    return vroom, version


def _write_json_atomic(path: Path, value) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.{uuid.uuid4().hex}.tmp")
    try:
        with temporary.open("w", encoding="utf-8", newline="\n") as handle:
            json.dump(value, handle, ensure_ascii=False, separators=(",", ":"))
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
    finally:
        temporary.unlink(missing_ok=True)


def _solve_file(
    input_path: Path,
    output_path: Path,
    *,
    exploration_level: int,
    threads: int,
    time_limit_seconds: float,
) -> dict:
    vroom, version = _require_runtime()
    if not input_path.is_file():
        raise RuntimeError(f"VROOM input file does not exist: {input_path}")
    if not 0 <= exploration_level <= 5:
        raise RuntimeError("VROOM exploration level must be between 0 and 5")
    if threads < 1:
        raise RuntimeError("VROOM worker threads must be at least 1")

    problem = vroom.Input.from_json(input_path, geometry=False)
    timeout = timedelta(seconds=time_limit_seconds) if time_limit_seconds > 0 else None
    solution = problem.solve(
        exploration_level=exploration_level,
        nb_threads=threads,
        timeout=timeout,
    )

    # pyvroom 1.15.2 does not infer this flag when a problem is loaded from a
    # custom distance matrix, so ``to_dict`` otherwise omits valid distance
    # values.  Every problem generated by this application includes distances.
    solution._distances = True
    response = solution.to_dict()
    wrapper = {
        "protocol_version": PROTOCOL_VERSION,
        "solver_backend": SOLVER_BACKEND,
        "solver_version": version,
        "result": response,
    }
    _write_json_atomic(output_path, wrapper)
    return wrapper


def _self_check() -> dict:
    vroom, version = _require_runtime()
    payload = {
        "jobs": [
            {
                "id": 1,
                "location_index": 1,
                "delivery": [1],
                "service": 1,
                "time_windows": [[0, 60]],
            }
        ],
        "vehicles": [
            {
                "id": 1,
                "profile": "car",
                "start_index": 0,
                "end_index": 0,
                "capacity": [1],
                "time_window": [0, 60],
            }
        ],
        "matrices": {
            "car": {
                "durations": [[0, 1], [1, 0]],
                "distances": [[0, 1], [1, 0]],
                "costs": [[0, 1], [1, 0]],
            }
        },
    }

    with tempfile.TemporaryDirectory(prefix="vroom_worker_check_") as temp_dir:
        input_path = Path(temp_dir) / "check.json"
        input_path.write_text(
            json.dumps(payload, ensure_ascii=False, separators=(",", ":")),
            encoding="utf-8",
        )
        problem = vroom.Input.from_json(input_path, geometry=False)
        solution = problem.solve(
            exploration_level=0,
            nb_threads=1,
            timeout=timedelta(seconds=5),
        )
        result = solution.to_dict()

    route_count = len(result.get("routes") or [])
    if result.get("code") != 0 or route_count != 1:
        raise RuntimeError(f"VROOM mini solve failed: {result!r}")

    return {
        "ok": True,
        "kind": "self_check",
        "protocol_version": PROTOCOL_VERSION,
        "solver_backend": SOLVER_BACKEND,
        "solver_version": version,
    }


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="CVRP VROOM companion worker")
    parser.add_argument("--self-check", action="store_true")
    parser.add_argument("--input", type=Path)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--exploration", type=int, default=5)
    parser.add_argument("--threads", type=int, default=4)
    parser.add_argument("--limit", type=float, default=0.0)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    try:
        if args.self_check:
            print(json.dumps(_self_check(), ensure_ascii=False), flush=True)
            return 0

        if args.input is None or args.output is None:
            raise RuntimeError("--input and --output are required for a solve")
        _solve_file(
            args.input.resolve(),
            args.output.resolve(),
            exploration_level=int(args.exploration),
            threads=int(args.threads),
            time_limit_seconds=float(args.limit),
        )
        return 0
    except Exception as exc:
        error = {
            "ok": False,
            "kind": "error",
            "protocol_version": PROTOCOL_VERSION,
            "solver_backend": SOLVER_BACKEND,
            "error_type": type(exc).__name__,
            "error": str(exc),
        }
        print(json.dumps(error, ensure_ascii=False), file=sys.stderr, flush=True)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
